src/Blogger/BlogBundle/Form/CommentType.php
<?php

namespace Blogger\BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class CommentType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user')
            ->add('comment')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Blogger\BlogBundle\Entity\Comment'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'blogger_blogbundle_comment';
    }
}

src/Blogger/BlogBundle/Resources/views/Page/about.html.twig
{% extends 'BloggerBlogBundle::layout.html.twig' %}

{% block title %}About{% endblock %}

{% block body %}
    <header>
        <h1>About symblog</h1>
    </header>
    <article>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit.
            Atque enim facilis laborum numquam repellendus saepe sint.
            Aliquid fugiat magnam modi pariatur perspiciatis possimus
            reprehenderit saepe similique ut voluptas. At corporis culpa
            cum cumque cupiditate debitis delectus doloremque dolores
            dolorum enim est exercitationem expedita fuga id illo illum
            incidunt inventore ipsa iste minus molestias nobis nostrum
            nulla numquam odio porro quaerat, qui quos repellendus reprehenderit
            rerum, similique sint sit ut velit vitae voluptatibus. Deserunt
            ducimus, enim. Ab, alias, aliquid amet architecto commodi earum
            eius ex explicabo harum illum ipsum minima neque nulla perferendis
            provident quis, quo reiciendis repellat repellendus vero voluptatibus!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit.
            Atque enim facilis laborum numquam repellendus saepe sint.
            Aliquid fugiat magnam modi pariatur perspiciatis possimus
            reprehenderit saepe similique ut voluptas. At corporis culpa
            cum cumque cupiditate debitis delectus doloremque dolores
            dolorum enim est exercitationem expedita fuga id illo illum
            incidunt inventore ipsa iste minus molestias nobis nostrum
            nulla numquam odio porro quaerat, qui quos repellendus reprehenderit
            rerum, similique sint sit ut velit vitae voluptatibus. Deserunt
            ducimus, enim. Ab, alias, aliquid amet architecto commodi earum
            eius ex explicabo harum illum ipsum minima neque nulla perferendis
            provident quis, quo reiciendis repellat repellendus vero voluptatibus!
        </p>
    </article>
{% endblock %}

src/Blogger/BlogBundle/Resources/views/Page/contact.html.twig
{% extends 'BloggerBlogBundle::layout.html.twig' %}

{% block title %}Kontakt{% endblock %}

{% block body %}
    <header>
        <h1>Kontakt z blogiem</h1>
    </header>

    {% for flashMessage in app.session.flashBag.get('blogger-notice') %}
        <div class="blogger-notice">
            {{ flashMessage }}
        </div>
    {% endfor %}


    <p>Want to contact symblog?</p>

    <form action=" {{ path('BloggerBlogBundle_contact') }}" method="post" {{ form_enctype(form) }} class="blogger">
        {{ form_errors(form) }}

        {{ form_row(form.name) }}
        {{ form_row(form.email) }}
        {{ form_row(form.subject) }}
        {{ form_row(form.body) }}

        {{ form_rest(form) }}

        <input type="submit" value="Wyślij" />
    </form>
{% endblock %}

src/Blogger/BlogBundle/Resources/views/Page/contactEmail.txt.twig
A contact enquiry was made by {{ enquiry.name }} at {{ "now" | date("Y-m-d H:i") }}.

Reply-To: {{ enquiry.email }}
Subject: {{ enquiry.subject }}
Body:
{{ enquiry.body }}

src/Blogger/BlogBundle/Resources/views/Page/index.html.twig
{% extends 'BloggerBlogBundle::layout.html.twig' %}

{% block body %}
    {% for blog in blogs %}
        <article class="blog">
            <div class="date">
                <time datetime="{{ blog.created|date('c') }}">{{ blog.created|date('l, F j, Y') }}</time>
            </div>
            <header>
                <h2><a href="{{ path('BloggerBlogBundle_blog_show', { 'id': blog.id}) }}">{{ blog.title }}</a></h2>
            </header>

            <img src="{{ asset(['images/', blog.image]|join) }}"/>

            <div class="snippet">
                <p>{{ blog.blog(500) }}</p>

                <p class="continue"><a href="{{ path('BloggerBlogBundle_blog_show', { 'id': blog.id }) }}">Kontynuuj
                        czytanie...</a></p>
            </div>
            <footer class="meta">
                <p>Comments: <a href="{{ path('BloggerBlogBundle_blog_show', {'id': blog.id}) }}#comments"> {{ blog.comments|length }}</a></p>

                <p>Posted by <span class="highlight">{{ blog.author }}</span> at {{ blog.created|date('h:iA') }} </p>

                <p>Tagi: <span class="highlight">{{ blog.tags }}</span></p>
            </footer>
        </article>
    {% else %}

        <p>Brak wpisów na blogu</p>
    {% endfor %}

{% endblock %}